### ISSUE TITLE
Optimize reading disjoint levels

### ISSUE THREAD

**Issue by marvin-j97** [fjall-rs/lsm-tree#26]
Reading disjoint levels needs to be smarter...

- [x] the check if a level is disjoint needs to be very fast, it should probably be cached inside each Level (Level.is_disjunct: bool), and only recalculated after level changes to avoid unnecessary work
- [x] benchmarks can already be found, see `tree_get_pairs`
- [x] need unit tests for first/last kv for different states of the tree, and for functions like Level::is_disjunct
- [x] check for disjoint levels and use MultiReader for tree iter/range/prefix ops
- [x] Tree::iter, ::range, ::prefix tests over disjoint levels

### Reading disjoint level current behaviour
Uses MergeIterator
![image](https://github.com/fjall-rs/lsm-tree/assets/33938500/35bc81c8-dcc3-4ef1-ad7a-f601e7b5a7dd)
First blocks of all segments are loaded, then compared to get minimum key.
![image](https://github.com/fjall-rs/lsm-tree/assets/33938500/466cef10-83cc-4869-b001-d25137b934c1)
After that, blocks are cached inside the iterator, so only once the first block is consumed, the next block is pulled.

### Reading disjoint level optimized version
Uses MultiReader
![image](https://github.com/fjall-rs/lsm-tree/assets/33938500/9c9f8186-ff44-4533-abcc-582f417c8a8d)
Once block is consumed, pull next block.
![image](https://github.com/fjall-rs/lsm-tree/assets/33938500/c364a679-89cb-4358-b7d8-362f25768087)
Once segment is consumed, start loading block of next segment.
![image](https://github.com/fjall-rs/lsm-tree/assets/33938500/5920e599-1bc9-4bb1-a1f3-230952ff0644)

For a full range scans, the there is no change in performance, as the blocks would need to be loaded anyway. But for operations like:
- Tree first/last kv
- is_empty
- ranges or prefixes that cover many segments, but are not fully read (i.e. .prefix("a").take(10))

the performance impact can be noticeable, as the number of I/O ops is O(n), n = number of segments, and especially Levelled compaction has typically more segments than Tiered (but disjoint). With the optimization, the number of I/O ops is O(f), f = number of non-empty levels, so typically O(7) ~ O(1)
