### ISSUE TITLE
[Tracking] Breaking changes in V2

### ISSUE THREAD

**Issue by marvin-j97** [fjall-rs/lsm-tree#41]
- [x] SingleDelete #38 
- [x] Key-value separation #1 
- [x] Use varint encoding #40 
- [x] Extensible compression support, Miniz compression #29
